### ISSUE TITLE
!!! Cannot deal with multiple number of pulse width entries yet!  Sorry.

### ISSUE THREAD

**Issue by sailukar** [sid5432/pubOTDR#1]
Hi Sid,

Did you figure out a way to fix the above message ?

**Comment by sid5432** [comment]
Hi,

I have only looked at a very small number of SOR files, and never came across examples with more than one pulse width entry. As result, I am not confident how the data should be interpreted in those cases. If you are interested in modifying the code to fix this to handle more than one pulse width entry, the place is in the fdxparams.pm file. 

If I remember correctly, in the SOR file, the number of pulse width entries is encoded as 2 bytes, followed by the pulse width (2 bytes), sample spacing (2 bytes) and number of data points (4 bytes). These are suppose to be repeated for the number of pulse width entries (have a look at <A HREF="http://morethanfootnotes.blogspot.com/2015/07/the-otdr-optical-time-domain.html">my blog</A> for some details). But I don't have sample files to confirm this, so I never tried to fix this.
