### ISSUE TITLE
How to use it from web browser

### ISSUE THREAD

**Issue by jaljaljal** [sid5432/pubOTDR#2]
I XAMPP web server . simply using the scripts in cgi-bin doesnt work to use it from web browser. Help pls to use it from web browser

**Comment by sid5432** [comment]
The code in pubOTDR was intended to be a module that you pull into your own code. I wrote a simple wrapper (read_otdr.pl) as a reference and demo. It of course will not run in a web browser! To do that, you will have to write your own wrapper. At the very least, you will need the perl CGI module (or something similar) to understand web requests. The other problem you need to figure out is how to get the SOR files to the web server. Will this be upload-once and process and throw away? Or are you looking for some permanent storage? Then there is the question of how you want to view the results. At the very least, you need to write a "Content-type" header in front of the output (that will be sent back to the web browser), even if you are not doing any fancy HTML formatting.

**Comment by jaljaljal** [comment]
Thank you

Any way I have done it. First converted .sor in to BLOB and stored in db (mysql) .  In LAMP platform using php shell_exec() 

/*  FOR TESTING */
$tmp_name="/usr/myloc/pubotdr/data/demo_ab.sor";
$fp = fopen($tmp_name, 'rb');
$file_content = file_get_contents($tmp_name);
/**/
$file_content=$_POST['content'];
$db->query("insert into test.blo (dat) values ('".mysql_real_escape_string($file_content)."') ");


// Then fetch the data(BLOB) from db and stored in a temp location 

$perl = shell_exec("/usr/home/pubotdr/read_otdr.pl /usr/temp_sor/dem.sor yes 2>&1");
echo ($perl);

 // GOT OUTPUT when executed from web browser
